name: CI
on: [push]
permissions:
  contents: read
  packages: write

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: MariaBolbotenko/DevOps_academy

      - name: Install node
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install packages
        run: npm i

      - name: Run eslint
        run: npm run lint 
