name: CI
on: [push]
permissions:
  contents: read
  packages: write

jobs:
  eslint:
    name: Lint code base
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: action/checkout@v4
          with:
            repository: MariaBolbotenko/DevOps_academy
            token: ${{ secrets.GITHUB_TOKEN }}
            ref: master

      - name: Install packages
        run: npm i

      - name: Run eslint
        run: npm run lint 
